/* AUTH ACTIONS */
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

/* TRAVEL ACTIONS */
export const CRAWLING_START = 'CRAWLING_START';
export const CRAWLING_SUCCESS = 'CRAWLING_SUCCESS';
export const CRAWLING_FAILED = 'CRAWLING_FAILED';
export const CRAWLING_ERROR = 'CRAWLING_ERROR';
export const ADD_FLIGHT_TO_STACK = 'ADD_FLIGHT_TO_STACK';
export const ADD_ACCOMODATION_TO_STACK = 'ADD_ACCOMODATION_TO_STACK';
export const SELECT_FLIGHT_TICKET = 'SELECT_FLIGHT_TICKET';
export const DESELECT_FLIGHT_TICKET = 'DESELECT_FLIGHT_TICKET';
export const SELECT_ACCOMODATION = 'SELECT_ACCOMODATION';
export const DESELECT_ACCOMODATION = 'DESELECT_ACCOMODATION';
export const SAVE_TRAVEL_ID = 'SAVE_TRAVEL_ID';

/* DASHBOARD ACTIONS */
export const GET_INITIAL_DATA_PENDING = 'GET_INITIAL_DATA_PENDING';
export const GET_INITIAL_DATA_SUCCESS = 'GET_INITIAL_DATA_SUCCESS';
export const GET_INITIAL_DATA_FAILED = 'GET_INITIAL_DATA_FAILED';

