/* AUTH ACTIONS */
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';

/* TRAVEL ACTIONS */
export const CRAWLING_START = 'CRAWLING_START';
export const CRAWLING_SUCCESS = 'CRAWLING_SUCCESS';
export const CRAWLING_FAILED = 'CRAWLING_FAILED';
export const CRAWLING_ERROR = 'CRAWLING_ERROR';

